name: 'Version Generator'
description: 'A GitHub Action that will generate a version string for publishing artefacts based on the branch and build time'
branding:
  icon: sliders
  color: purple
inputs:
  branch:
    description: 'The branch name. Assign from github.ref. Example, "refs/heads/main".'
    required: true
  dir:
    description: 'The root directory to work from. Example, "path/to/code".'
    required: true
  versionFilename:
    description: 'The name of the file that holds the x.x.x version'
    required: true
outputs:
  artefact-version:
    description: 'The Version string in a x.y.z-branch-buildTime format'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-b'
  - ${{ inputs.branch }}
  - '-d'
  - ${{ inputs.dir }}
  - '-v'
  - ${{ inputs.versionFilename }}